### ISSUE TITLE
Enable Emilie Esposito to modify main statements e.g. Universal Basic Income

### ISSUE THREAD

**Issue by emilieagreelist** [hectorperez/agreelist#31]

**Comment by hectorperez** [comment]
I think you already have permissions to do that. It's just that there is no visible link for now.

Could you try to add /edit to the url? E.g. http://www.agreelist.org/s/advanced-artificial-intelligenc-4mtqyes0jrqy/edit

By the way, regarding the tags of the form, I'd wait until we talk about this before changing them.
