### ISSUE TITLE
Allow opinions on basic income (and others) to be sorted by profession

### ISSUE THREAD

**Issue by emilieagreelist** [hectorperez/agreelist#48]
Similarly to what we did for AgreeList.org/brexit

**Comment by hectorperez** [comment]
It's already there for topics with at least a few opinions. For example on basic income click on 228 influencers. Do you mean this?

**Comment by emilieagreelist** [comment]
Oh I see! I believe then we should make it more visible as I had never
noticed it.

Maybe we could add a line saying something like opinions per professions?

Also, looking at the basic income opinions per profession and it seems that
the top profession has 26 opinions vs. 226 top opinions, and the total
amount of opinions per professions is probably around 100. Are there that
many opinions unclassified? Or is it because we are missing out some
categories? Let me know what you think and whether there's something I can
do from here to improve the quality of data

Best
Emilie

**Comment by hectorperez** [comment]
We could try something to make it clearer, although we'd like not to try to add much more text.

Regarding the number of professions, right now we only consider the professions taken from Wikidata.
- First, there is a bug that prevents the app from getting the data when the wikipedia link is to a non English wikipedia page.
- Second, we could update the data from Wikidata for the people on AgreeList with Wikipedia link but with no profession (going to the Wikidata site or adding a functionality from AgreeList to do so from there, if this is possible).
- Third, we'll have to think what to do for people with no Wikidata/Wikipedia page.

**Comment by emilieagreelist** [comment]
Great thank you! I guess now the priority is to update the mailing list so
we can send out the July newsletter
Cheers,
Emilie

**Comment by hectorperez** [comment]
Now it’s a bit clearer because of the pie charts you can click to filter per profession
