### ISSUE TITLE
Make sure that if one clicks onto the source of an opinion etc, this leads to a new page

### ISSUE THREAD

**Issue by emilieagreelist** [hectorperez/agreelist#49]
This will facilitate browsing through opinions on Agreelist
The same comment also applies when one clicks on the Wikipedia and Twitter links

**Comment by hectorperez** [comment]
I'd like to see what the best practices are for this

**Comment by emilieagreelist** [comment]
Sure - What I find a pity is that people always have to go back or research
where they were before they looked for a source etc. (and our search
function is basic as of now)

**Comment by hectorperez** [comment]
Done. Now it opens external links* in a new tab.

* source and wikipedia links from topics and twitter and wikipedia links from profiles. I don't remember if there are any more external links. If so, please let me know ;)
