### ISSUE TITLE
Allow both a short version and a long version of long opinions with a "More" function

### ISSUE THREAD

**Issue by emilieagreelist** [hectorperez/agreelist#50]
We have an issue with Scott Santens opinion on Job Guarantee: the opinion is far too long and there is no source. However, the opinion is good and we want to encourage these types of contributors (not offend them by deleting part of what they wrote for AgreeList). Therefore, we might want to keep his full contribution in the website, but only show a short extract visible with all other opinions, eg. the following: "Automation is what can finally free humanity. A job guarantee is the perpetuation of wage enslavement. Unemployment is not a disease. Involuntary jobs are the disease and unemployment is the cure. The goal of society should be full unemployment, not full employment". A "More" or "Read more" button would allow to access to the full opinion while not making other opinions more difficult to read

**Comment by hectorperez** [comment]
Good point! Actually, I hadn't read Scott's opinion but I was thinking the
same: display a max. number of characters by default and add a "more" link
as Facebook does.

**Comment by hectorperez** [comment]
Done
