### ISSUE TITLE
Change the automatic Tweet that one can send to influencers

### ISSUE THREAD

**Issue by emilieagreelist** [hectorperez/agreelist#53]
I would opt for a more personal text, mentioning AgreeList and inviting to take action: 
@[xxxx] your opinion re. "[topic]" is now on #AgreeList [shortened goo.gl link]. Let AgreeList know if you would like to modify it!

**Comment by hectorperez** [comment]
How about let me know instead of let AgreeList know?

@[xxxx] your opinion re. "[topic]" is now on #AgreeList [shortened
goo.gl link].
Let me know if you would like to modify it!

**Comment by hectorperez** [comment]
Done
