### ISSUE TITLE
Give back to Emilie Esposito the ability to modify/delete topics in agreelist.org/s

### ISSUE THREAD

**Issue by emilieagreelist** [hectorperez/agreelist#59]

**Comment by hectorperez** [comment]
As /s (same as /all) is public now, I moved the delete link to the edit page of a topic. But now we can only delete topics with no opinions.

To edit a topic add /edit after the URL of any topic. We'll have to add a link to this at some point though.

Let me know if you need anything else for now.

**Comment by hectorperez** [comment]
Hi Emilie,

I replied there.

Cheers,
Hector

**Comment by emilieagreelist** [comment]
Thank you Hector, I am not sure I understand - I don't see anymore the
"edit" function for the name of a topic (sometimes topics are awkwardly
phrased, or I find a better title eg. women-only instead of female-only in
the last topic I created, or I would like to add tags to facilitate the
search function) neither on the /all, /s or topic pages
Is there another place I should look at?
Thanks!
Emilie

**Comment by hectorperez** [comment]
I meant that the edit and delete links are not there anymore. As the page
is public now I removed them.

I could have made them visible only for us but then the list was quite
different to what normal users see and this has some disadvantages. We
should include the edit link there or probably in the topic page, but for
now you can add /edit at the end of the URL. For example for universal
basic income it's the following:
http://www.agreelist.org/s/universal-basic-income-kbupbtnz4sek/edit instead
of http://www.agreelist.org/s/universal-basic-income-kbupbtnz4sek

And in that page, at the end, you would see "delete" if the topic had no
opinions.

Is it clearer now?

Cheers

**Comment by emilieagreelist** [comment]
Great thanks!
