### ISSUE TITLE
Allow Emilie Esposito to promote opinions within a topic page

### ISSUE THREAD

**Issue by emilieagreelist** [hectorperez/agreelist#61]
This would allow her to put better known influencers on the top of the topic page without having to upvote anything. Please also cancel her upvotes in the "agree" section of the "female-only train carriage" topic

**Comment by hectorperez** [comment]
We have to see how to do this. Regarding cancelling upvotes, it's easier
for you. Any user can cancel her/his upvotes just clicking on "upvoted!".
The link is in the same place as the original "upvote".

**Comment by hectorperez** [comment]
We'll have to think and talk about this
