### ISSUE TITLE
Add Twitter @JasonTanz to Jason Tanz' opinion on "Social media threatens deocracy"

### ISSUE THREAD

**Issue by emilieagreelist** [hectorperez/agreelist#94]
I mistakenly added a former opinion and profile in the Disagree column, and then created a new opinion in the Agree column before deleting the first opinion. However, I was not able to include Jason Tanz' twitter address in his profile

**Comment by hectorperez** [comment]
Done

**Comment by hectorperez** [comment]
By the way, it's possible to do it editing his profile (I did it this way).
